# Server Port
server.port=7878

# Eureka Server Configuration
spring.application.name=gateway-service
eureka.client.serviceUrl.defaultZone=http://localhost:7777/eureka/
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true

# Gateway Routes Configuration
spring.cloud.gateway.routes[0].id=question-service
spring.cloud.gateway.routes[0].uri=lb://QUESTION-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/question-service/api/**









